### ISSUE TITLE
可以把数据格式化就更好了

### ISSUE THREAD

**Issue by chengfengfengwang** [Ceelog/DictionaryByGPT4#1]
如果可以把数据格式化，支持查询就更好了。可以弄成json格式？还是sqlite？之类的

**Comment by Ceelog** [comment]
原始 JSON 数据加上了，可以基于这个数据集二开

**Comment by chengfengfengwang** [comment]
> 原始 JSON 数据加上了，可以基于这个数据集二开

respect👍
