### ISSUE TITLE
对该库新增了发音，筛选功能

### ISSUE THREAD

**Issue by git-hub-cc** [Ceelog/DictionaryByGPT4#34]
代码库：https://github.com/gitpz/Subtitle-Vocabulary-Learning-Tool-GPT4
网站预览：https://gitpz.github.io/Subtitle-Vocabulary-Learning-Tool-GPT4/

**Comment by VeejaLiu** [comment]
一塌糊涂

**Comment by gitpz** [comment]
哎呀，被你发现了，简单搞搞是这样的啦。

**Comment by VeejaLiu** [comment]
并且主要是我没明白你的这个目的是啥，但是我隐约感觉十分有价值，但是你做的确实没有体现出来，且让人一头雾水，太可惜了。
